name: Deploy

on:
  push:
    branches:
      - akshay

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stark-island-21254" #Must be unique in Heroku
          heroku_email: "n10eta@gmail.com"
